### ISSUE TITLE
Will this project be abandoned??

### ISSUE THREAD

**Issue by JeysonFlores** [giraffelibrary/giraffe#1]
Hi! I'm researching for GTK bindings in all the possible programming languages because I want to make like an Enciclopedia of GTK in all the possible programming languages. I saw on the wiki that this library is the GTK binding for Standard ML, but it seems that it haven't been updated since april. I'm not really into the functional programming world but it seems like a quite efficient library.
Will you keep developing or it?

**Comment by pclayton** [comment]
Yes, the library is still being developed and used!  I have a number of unpushed commits in my local repository, e.g. to support Poly/ML 5.8.2.  I like to test changes on all platforms before pushing them, and I haven't got around to testing on Mac OS, which is why they're blocked.

**Comment by JeysonFlores** [comment]
That's great and thanks for your contributions! I'll try to run this library (even tho I've never used SML), to start tinkering with it.
