### ISSUE TITLE
Not able to locate constants

### ISSUE THREAD

**Issue by JeysonFlores** [giraffelibrary/giraffe#3]
Hello again! I started tweaking again with Giraffe but now with a more serious mood. I'm trying to instantiate a Gtk.Clipboard object using the following code:

```SML
val clipboard = Gtk.Clipboard.get Gdk.SELECTION_CLIPBOARD
```

According to Giraffe's docs: _"For a constant SOME_CONSTANT_NAME in a namespace Namespace, the hierarchical SML name is Namespace.SOME_CONSTANT_NAME. "_

However it gives me the following error:
```cmd
error: Value or constructor (SELECTION_CLIPBOARD) has not been declared in structure Gdk
Found near Gtk.Clipboard.get Gdk.SELECTION_CLIPBOARD
```
I searched for documentation in other bindings to see if it's due to that constant being in other Namespace or something but all the sources say that the place of `SELECTION_CLIPBOARD` is in `Gdk`.
Examples:
- [Vala](https://valadoc.org/gdk-3.0/Gdk.SELECTION_CLIPBOARD.html)
- [Rust](https://docs.rs/gdk/0.10.0/gdk/constant.SELECTION_CLIPBOARD.html)
- [Python](https://lazka.github.io/pgi-docs/#Gdk-3.0/constants.html#Gdk.SELECTION_CLIPBOARD)

**Comment by pclayton** [comment]
Giraffe Library is produced from GObject Introspection metadata so contains only items included by introspection.  There is a [list of excluded items](http://giraffelibrary.org/ug-excluded-log.html) but Gdk.SELECTION_CLIPBOARD is not one of them.  The source to look at is https://docs.gtk.org/ (for Gtk/Gdk 3, scroll down to 'older versions') which is produced from the GObject Introspection metadata, unlike the old [developer references](https://developer-old.gnome.org/references) that are more C-oriented.

There is actually [no such constant in `Gdk`](https://docs.gtk.org/gdk3/#constants).  The first paragraph of [`Gtk.Clipboard`](https://docs.gtk.org/gtk3/class.Clipboard.html) explains what is going on here.  You can create the `Gdk.Atom` argument for `Gtk.Clipboard.get`as follows:
```
Gdk.Atom.intern ("CLIPBOARD", false)
```

**Comment by pclayton** [comment]
Your Python reference is useful - it shows what to write instead!

**Comment by JeysonFlores** [comment]
> The source to look at is https://docs.gtk.org/ (for Gtk/Gdk 3, scroll down to 'older versions') which is produced from the GObject Introspection metadata

Got it. I think I was looking in the wrong docs.

> Your Python reference is useful - it shows what to write instead!

Fun fact, those little annotations weren't loading to me yesterday because of some connection issues I had so I didn't know what you were talking about until a few moments ago when I checked again the website and yes.

**Comment by JeysonFlores** [comment]
By the way, Are multi-parameter signals handled differently? I'm trying to connect a window's deletion event to a function like this:
```SML
    val _ = Signal.connect window (Widget.deleteEventSig, fn () => print "Even triggered")
```
I saw the gtk3 docs and the signal looks like this;
```c
gboolean
delete_event (
  GtkWidget* widget,
  GdkEventAny* event
)
```

```
Function: Signal.connect window :
      ((base Event.union -> bool) ->
        base application_window window bin container widget initially_unowned
        Signal.object_class Signal.t) * (base Event.union -> bool) ->
        Signal.id
   Argument: (Widget.deleteEventSig, fn () => print "Even triggered") :
      ((base Event.union -> bool) ->
        base application_window window bin container Widget.class Signal.t) *
      (unit -> unit)
   Reason: Can't unify base Event.union to {} (Incompatible types)
Found near Signal.connect window (Widget.deleteEventSig, fn () => ... ...)
Exception- Fail "Static Errors" raised
```
I think I'm missing the GdkEventAny* event parameter but I don't know where and how to put it in the signal creation. Even looking at the C code I don't identify what is the problem.

**Comment by pclayton** [comment]
The key line in the error message is
```
Reason: Can't unify base Event.union to {} (Incompatible types)
```
The signal hander is given a `Gdk.EventAny` but your pattern is `()` which has type `unit` (written in the error message as `{}`).  So changing `()` in the pattern to `_` should avoid the type error.  If the error message from a compiler isn't clear enough it may be worth building the other compiler to see if that error is any clearer.

**Comment by pclayton** [comment]
Out of interest, which documentation contained the description
```
gboolean
delete_event (
  GtkWidget* widget,
  GdkEventAny* event
)
```
?  According to [Gtk 3 docs](https://docs.gtk.org/gtk3/signal.Widget.delete-event.html), the argument is a `GdkEvent`, not a `GdkEventAny`.  I'm just curious - it may make sense to override this type in codegen to be a `GdkEventAny`.

**Comment by JeysonFlores** [comment]
> The signal hander is given a Gdk.Event but your pattern is () which has type unit (written in the error message as {}). So changing () in the pattern to _ should avoid the type error. If the error message from a compiler isn't clear enough it may be worth building the other compiler to see if that error is any clearer.

Oh, I see. Thanks for that hint!.

`Out of interest, which documentation contained the description`
Oh, I just searched for "delete_event" and it showed me [this](https://docs.gtk.org/gtk3/vfunc.Widget.delete_event.html) but according to it it's a virtual method and not a signal.
