### ISSUE TITLE
Update Makefile to accept DESTDIR

### ISSUE THREAD

**Issue by brabes** [giraffelibrary/giraffe#7]
When packaging this for Arch Linux, it is much easier if there is a DESTDIR variable, see for example https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fltk-git

I have created a pull request #6 that fixes this.

Thanks,

**Comment by giraffelibrary** [comment]
Thanks for the suggestion.  This should be added.

The patch (quite reasonably) assumes that `PREFIX` is absolute (starts with `/`) but I have realized that this is not checked in `configure`.  For a `configure` generated by Autoconf, `configure --prefix ..` would give an error like
```
configure: error: expected an absolute directory name for --prefix: ..
```
I will update `configure` to check that all prefix paths are absolute.

**Comment by giraffelibrary** [comment]
Raised #8 to update `configure`.
